name: Greetings

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - labeled
      - unlabeled
      - synchronize
  issues:

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.head_ref, 'dependabot/') }}
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message:  'Hello @${{ github.actor }}, thank you for submitting a PR! We will respond as soon as possible.'
        issue-message: |
          Hello @${{ github.actor }}, thank you for your interest in our work!

          If this is a bug report, please provide screenshots and **minimum viable code to reproduce your issue**, otherwise we can not help you.
